swagger: "2.0"
info:
  description: "Swagger doc for connections app"
  version: "1.0.0"
  title: "Connections"
schemes:
- "https"
- "http"
paths:
  /people:
    get:
      summary: "Get list of people"
      description: ""
      operationId: "getPeople"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "sort"
        type: "string"
        required: false
        description: "optional sort parameters: created_at, name. Prefix with (-) for desc."
      responses:        
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid input"

    post:
      summary: "Create a new person"
      description: ""
      operationId: "createPerson"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Person object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/Person"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Person"
        400:
          description: "Invalid input"

  /connections:
    get:
      summary: "Get list of connections"
      description: ""
      operationId: "getConnections"
      produces:
      - "application/json"
      responses:        
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"

    post:
      summary: "Create a new connection"
      description: ""
      operationId: "createConnection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Connection object that needs to be created"
        required: true
        schema:
          $ref: "#/definitions/Connection"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Invalid input"

  /connections/{id}:
    patch:
      summary: "Modify an existing connection's type"
      description: ""
      operationId: "patchConnection"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "new type"
        description: "new connection_type value"
        required: true
        schema:
          type: "object"
          required:
            - "connection_type"
          properties:
            connection_type: 
              type: "string"
      - in: "path"
        name: "id"
        required: true
        schema:
          type: "integer"
        description: "The connection's id"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/Connection"
        400:
          description: "Input failed validation. Invalid connection_type."
        404:
          description: "The requested URL was not found on the server. 
                       If you entered the URL manually please check your 
                       spelling and try again."

    delete:
      summary: "Delete an existing connection"
      description: ""
      operationId: "deleteConnection"
      parameters:
      - in: "path"
        name: "id"
        required: true
        schema:
          type: "integer"
        description: "The connection's id"
      responses:
        204:
          description: "successful deletion"
        404:
          description: "The requested URL was not found on the server. 
                       If you entered the URL manually please check your 
                       spelling and try again."

definitions:
  Person:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"

  Connection:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      from_person_id:
        type: "integer"
        format: "int64"
        description: "From Person"
      to_person_id:
        type: "integer"
        format: "int64"
        description: "To Person"
      connection_type:
        type: "string"
        description: "Connection Type"
        enum:
        - "mother"
        - "father"
        - "son"
        - "daughter"
        - "husband"
        - "wife"
        - "brother"
        - "sister"
        - "friend"
        - "coworker"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
